version: "3"
services:
  opa:
    image: quay.io/jmprusi/opa-http-extauthz:latest
    ports:
      - 9292:9292
    command:
      - "run"
      - "--server"
      - "--log-format=json-pretty"
      - "--set=decision_logs.console=true"
      - "-c"
      - "/tmp/opa/opa.config"
      - "/tmp/opa/authz.rego"
    volumes:
      - "./opa:/tmp/opa:rw"
  openresty:
    build:
      context: ./openresty 
    volumes:
      - "./openresty/conf/:/etc/nginx/conf.d/"
    ports:
      - 8080:8080
  envoy:
    build:
      context: ./envoy
    command:
      - "envoy"
      - "-c" 
      - "/tmp/envoy.yaml"
    ports:
      - 8081:8081
  helloworld:
    build:
      context: ./helloworld
    ports:
      - 1234:1234
