apiVersion: v1
kind: Service
metadata:
  name: opa
  labels:
    app: opa
    service: opa
spec:
  ports:
  - name: http
    port: 9292
    targetPort: 9292
  selector:
    app: opa
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opa
  labels:
    app: opa 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opa
  template:
    metadata:
      labels:
        app: opa
    spec:
      containers:
      - image: quay.io/jmprusi/opa-http-extauthz:latest
        imagePullPolicy: IfNotPresent
        name: opa
        ports:
        - containerPort: 9292
        args:
          - "run"
          - "--server"
          - "--log-format=json-pretty"
          - "--set=decision_logs.console=true"
          - "-c"
          - "/tmp/opa/opa.config"
          - "/tmp/opa/authz.rego"
        volumeMounts:
          - name: config
            mountPath: /tmp/opa
            readOnly: true
      volumes:
        - name: config
          configMap:
            name: opa-config
            items:
              - key: opa-config
                path: opa.config
              - key: authz
                path: authz.rego
